#Requires -Version 7.4
#Requires -PSEdition Core
# Pester tests for dot_config/herdr/pane-translate.ps1 — the text pipeline behind
# prefix+t and the "Translate pane" Quick Actions.
#
# THE POINT OF THIS FILE IS CROSS-REPO PARITY. `Format-HerdrCapture` here is a
# hand port of an embedded python3 filter in the parent repo's
# dot_config/herdr/executable_pane-translate.sh. Nothing in either repo's build
# would notice the two drifting apart, and the failure mode is expensive and
# silent: a capture that translates on macOS but comes back verbatim on Windows
# still exits 0 and still bills an LLM call.
#
# So the fixtures under tests/fixtures/herdr/ are BYTE-IDENTICAL COPIES of the
# parent repo's, expectations included, and those expectations were generated by
# the unix filter. `tests/unit/herdr_pane_translate.bats` over there asserts the
# same pairs. If you change one implementation, regenerate the fixtures there,
# copy them here, and make both suites green — do not hand-edit an expectation.
#
# Two behaviours are non-obvious and have already bitten:
#
#   1. THE MODAL DEDENT. translate's bitext classifies a block as *code* once its
#      indent is >= base + 2. An agent pane renders prose behind a uniform left
#      margin while turn markers sit at column 0, so a min()-based base dedents
#      nothing and the ENTIRE page comes back untranslated.
#   2. `visible` IS NEVER TRIMMED AT THE TOP — it is literally what the user is
#      looking at. Only `recent:N` windows may be snapped to a block boundary.
#
# Nothing here contacts herdr or translate: only Format-HerdrCapture is loaded,
# so the suite passes on windows-latest with neither installed.

BeforeAll {
    $RepoRoot = Join-Path $PSScriptRoot '..'
    $Helper   = Join-Path $RepoRoot 'dot_config' 'herdr' 'pane-translate.ps1'
    $FixDir   = Join-Path $PSScriptRoot 'fixtures' 'herdr'

    # Extract just the filter. Dot-sourcing the whole script would pull in
    # _common.ps1 and run the capture side against a real server.
    $src = Get-Content -Raw -LiteralPath $Helper
    $from = $src.IndexOf('function Format-HerdrCapture {')
    $to = $src.IndexOf('function Invoke-HerdrTranslate {')
    if ($from -lt 0 -or $to -le $from) { throw 'Format-HerdrCapture not found in pane-translate.ps1' }
    Invoke-Expression $src.Substring($from, $to - $from)

    function Invoke-Filter {
        param([string] $Fixture, [string] $Mode, [int] $Budget = 12000)
        $raw = Get-Content -Raw -LiteralPath (Join-Path $FixDir $Fixture)
        (Format-HerdrCapture -Lines ($raw -split "`r?`n") -Mode $Mode -Budget $Budget).Text
    }

    function Get-Expected {
        param([string] $Name)
        ((Get-Content -Raw -LiteralPath (Join-Path $FixDir $Name)) -replace "`r`n", "`n").TrimEnd("`n")
    }
}

Describe 'pane-translate.ps1 parses' {
    It 'is syntactically valid PowerShell' {
        $errors = $null
        $null = [System.Management.Automation.Language.Parser]::ParseFile($Helper, [ref] $null, [ref] $errors)
        $errors | Should -BeNullOrEmpty
    }
}

Describe 'Format-HerdrCapture matches the unix filter byte for byte' {
    It 'visible: agrees with the expectation generated by the unix helper' {
        Invoke-Filter 'pane-capture.txt' 'visible' | Should -BeExactly (Get-Expected 'pane-capture.visible.expected')
    }

    It 'recent: agrees on a capture whose top edge falls mid-sentence' {
        Invoke-Filter 'pane-capture-midcut.txt' 'recent:200' |
            Should -BeExactly (Get-Expected 'pane-capture-midcut.recent.expected')
    }

    It 'visible: agrees that the same mid-sentence capture is kept whole' {
        Invoke-Filter 'pane-capture-midcut.txt' 'visible' |
            Should -BeExactly (Get-Expected 'pane-capture-midcut.visible.expected')
    }
}

Describe 'bottom chrome is removed, content is not' {
    BeforeAll { $script:out = Invoke-Filter 'pane-capture.txt' 'visible' }

    It 'drops the status-line block, the prompt row and the spinner' {
        $out | Should -Not -Match 'Tokens 4\.6M'
        $out | Should -Not -Match 'bypass permissions'
        $out | Should -Not -Match '~statistics\.json'
        $out | Should -Not -Match 'Percolating'
    }

    It 'keeps every line of real transcript' {
        $out | Should -Match 'The TUI currently renders'
        $out | Should -Match 'Edit docs/parity-matrix\.md'
    }

    It 'collapses a hidden-transcript marker to a bare ellipsis' {
        $out | Should -Not -Match '\+194 lines'
        $out | Should -Match '\[…\]'
    }

    It 'yields nothing at all for an all-chrome capture' {
        $lines = @('❯', '  -- INSERT -- ⏵⏵ bypass permissions on (shift+tab to cycle)')
        (Format-HerdrCapture -Lines $lines -Mode 'visible' -Budget 12000).Text | Should -BeExactly ''
    }
}

Describe 'the modal dedent' {
    BeforeAll { $script:out = Invoke-Filter 'pane-capture.txt' 'visible' }

    It 'brings prose to column 0 even though turn markers sit at column 0 already' {
        # A min()-based base would be 0 here and dedent nothing — the bug this
        # whole test file exists for.
        $out | Should -Match "(?m)^The TUI currently renders"
    }

    It 'leaves a deeper code block indented, so translate still treats it as code' {
        $out | Should -Match "(?m)^ {4}\`$ just bats"
    }
}

Describe 'the character budget' {
    It 'trims from the top, marks the cut, and keeps the newest content' {
        $out = Invoke-Filter 'pane-capture-midcut.txt' 'recent:200' 60
        $out.Length | Should -BeLessThan 200
        $out | Should -Match 'omitted'
        $out | Should -Match 'Preserve lazy live loading'
    }
}
